name: Docker

on:
  push:
    branches:
      - master
      - docker

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Build wheel
      shell: bash
      env:
        BUILD_WHEEL: true
        OS: linux
      run: |
        source ./scripts/ci.sh
    - name: Build docker
      shell: bash
      run: |
          docker build -f docker/Dockerfile . -t keyiz/kratos
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push keyiz/kratos:latest
          docker tag keyiz/kratos docker.pkg.github.com/kuree/kratos/py38:latest
          docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
          docker push docker.pkg.github.com/kuree/kratos/py38:latest

          # build the full one
          docker build -f docker/Dockerfile-Cad . -t keyiz/kratos-full
          docker push keyiz/kratos-full:latest
      env:
        GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/upload-artifact@v1
      with:
        name: py3.7 wheel
        path: wheelhouse/
