name: MacOS Wheel Test

on: [push]

jobs:
  build:

    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Setup Env
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.7
    - name: Install verilator
      shell: bash
      run: |
          brew install verilator
          verilator --version
    - name: Install Python packages
      shell: bash -l {0}
      run: |
          pip install wheel pytest
    - name: Build and run wheel
      shell: bash -l {0}
      env:
        OS: osx
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        # miniconda uses 10.13
        MACOSX_DEPLOYMENT_TARGET: 10.13
        KRATOS_DEBUG: 1
      run: |
        source ./scripts/ci.sh
    - uses: actions/upload-artifact@v1
      with:
        name: py3.7 wheel
        path: dist/
