services:
    - docker

matrix:
  include:
  - os: linux
  - os: osx
    osx_image: xcode10.2
before_install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
    chmod +x miniconda.sh
    ./miniconda.sh -b -p $TRAVIS_BUILD_DIR/miniconda
    export PATH=$TRAVIS_BUILD_DIR/miniconda/bin:$PATH
    hash -r
    conda config --set always_yes yes --set changeps1 no
    conda update -q conda
    conda create -q -n test-env python=3.7.3
    source activate test-env
    conda install pip
    pip install z3
  fi
install:
- echo $TRAVIS_BRANCH
- echo $TRAVIS_OS_NAME
- echo $TRAVIS_BUILD_DIR
- source ./.travis/setup.sh

script:
- source ./.travis/run.sh

deploy:
- provider: script
  script: /bin/bash .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master
    tags: true

notifications:
  slack:
    rooms:
      secure: vYqmNj2HcykuryVM6+KYnkT6XoAGhV+W90ln/hVrniUeGutZ5R/fxlF8T8zOtmM/CxcqPbsa/awusSiX77Xegrf8gEcdUy6Jmvlz68F89wmkua4RuMoUnymRoNNE+YE1jrNO/39X+gDSEbYlCob5TtWXBAlGDfIJ8rjaP9LJV1Y6lDvJeCp/k9RcJDs9OlPaGP237pWJUIKEN1BnGyAFSQbbdLF+mTg7BcZr5pT9iuNQAyjrZcle/DPdLg5V+C4IQCkA8lXnI2ushuL3xmrjQ4TBvUNrGojKTTir3fXkeU+Zed2jukvRVKjDyiKV2gWr1tqM3Nl3U7JIkJpTu6HxwRI16l2M35eE/1kmJ817AEc/2RepI6tPEYi3aLtAbLldltuYiiUvDVsf9sMS8ireqoHXEaPJD6IkrMp4Tm9TO/b267fC3lvrRYd927NjKlV0Pk/ZgcPKoNjP8aPxj2+FvoPlExdjEvwHFxWpTRzqnHJudYeKScFzSlFAW+vMIpNZ2JMBwcKL2ENwBIGX5T8mkkvKJcZGUS1Sv1sIqVaPuINW058a4ARSl/JHkE6KUW+452uOfWMhz+XD4NjOaAWK9So9Zw8g+x52+F5k4mlK7bkosqpkQ6uWYtHM42Wz2OYz2rL4S2EtetJf4/vLRAgzhRdmo9RDrYPRtInW8jcm7nM=
